language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - rbx-2
  - jruby
env:
  - "rake=0.8"
  - "rake=0.9"
  - "rake=10"
script: "bundle exec rspec"
notifications:
  email:
   - gabrijel.skoro@infinum.hr
   - stjepan.hadjic@infinum.hr
